### ISSUE TITLE
Mopidy3/Python3 Compatibility

### ISSUE THREAD

**Issue by djmattyg007** [aawsome/mopidy-snapcast#7]
Is there any interest in upgrading this extension to support Mopidy 3?

**Comment by aawsome** [comment]
Thanks for asking! In fact, I lost a bit track of the Mopidy development... I think that Python 3 should not be an issue and I'll have a look at Mopidy 3

**Comment by wvangulik** [comment]
Hi @aawsome ,

I just tried out and I have some debugging output that might help :  (sorry if I'm not posting that to the right place, I'm not that git-fluent ;) )

```
Jan 22 11:37:21 localhost mopidy[11538]: ERROR    [MainThread] mopidy.__main__ Extension snapcast failed during setup. This might have left the registry in a bad state.
Jan 22 11:37:21 localhost mopidy[11538]: Traceback (most recent call last):
Jan 22 11:37:21 localhost mopidy[11538]:   File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 129, in main
Jan 22 11:37:21 localhost mopidy[11538]:     extension.setup(registry)
Jan 22 11:37:21 localhost mopidy[11538]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_snapcast/__init__.py", line 28, in setup
Jan 22 11:37:21 localhost mopidy[11538]:     from .mixer import SnapcastMixer
Jan 22 11:37:21 localhost mopidy[11538]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_snapcast/mixer.py", line 60
Jan 22 11:37:21 localhost mopidy[11538]:     self.trigger_volume_changed(self.get_volume())
Jan 22 11:37:21 localhost mopidy[11538]:                                                  ^
Jan 22 11:37:21 localhost mopidy[11538]: TabError: inconsistent use of tabs and spaces in indentation
Jan 22 11:37:21 localhost mopidy[11538]: INFO     [MainThread] mopidy_mowecl VERSION 0.4.0
Jan 22 11:37:21 localhost mopidy[11538]: ERROR    [MainThread] mopidy.commands Did not find unique mixer "snapcast". Alternatives are: software, none

```

**Comment by chris-aeviator** [comment]
@wvangulik  after fixing the identation bugs (replace tabs with spaces) I will see another error

```
Apr 27 19:39:19 raspberrypi mopidy[2375]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_snapcast/mixer.py", line 9, in <module>
Apr 27 19:39:19 raspberrypi mopidy[2375]:     from snapcast_socket import snapcast
Apr 27 19:39:19 raspberrypi mopidy[2375]: ModuleNotFoundError: No module named 'snapcast_socket'

```

**Comment by zessi001** [comment]
Hello,
i modified some minor things and its working very good. Changed logic to identify group ids. Regular expression was only working without pathes and same mount on mopidy and snapserver groups.
Not sure, how to distribute it here if some one is interested in code. 
I am using it with mopidy 3.4.2 and musicbox_webinterface/iris. The volume slider is now same as in Snapweb and it changes volume really smooth.
best regards
